title: Temporario
description: "This project aims to create a mobile application that functions as a calendar, for personal time management, called Temporario. The app should allow a new user to register. Once registered, a user can:
- see the updated calendar
- add events to the calendar
- see the details of each event and modify them
- delete events from the calendar
The application will consist of a data persistence server that uses Firestore Cloud, the backend part that manages all the functionalities listed above, and the frontend part with a graphical interface used by users. The authentication and authorization will be based on the Google Sign-In API. The whole application will be developed in Android Studio, using Kotlin."
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
